# If storing sensitive variables, it's recommended to encrypt the file. See ansible-vault documentation for details
# Example ansible-vault encrypt: ansible vault --vault-id yourId@prompt razer-blade-stealth.yml
vault:
  username: 'vault_username'
  password: 'vault_password'
  uri: 'https://vault.example.com'

ssh_keys:
  - key_name: 'my-server-ssh-key'
    ssh_contents: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/my-secret/path auth_method=userpass mount_point=userpass username={{ vault.username }} password={{ vault.password }} url={{ vault.uri }}')['my-server-ssh-key'] }}"
    host_list: my-server-1 my-server-2 my-server-3
  - key_name: 'my-github-ssh-key'
    ssh_contents: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/my-secret/path auth_method=userpass mount_point=userpass username={{ vault.username }} password={{ vault.password }} url={{ vault.uri }}')['my-github-ssh-key'] }}"
    host_list: github.com
