all:
  hosts:
    inspiron-7610:
    razer-blade-stealth:
  children:
    ubuntu:
      hosts:
        inspiron-7610:
          general_directories_enabled: true
          general_configs_content_enabled: true
          ws_home_dir: "/home/username"
          ws_username: "username"
          ssh_configure: true
          os_type: "linux"
          architecture: "amd64"
          packages:
            - nodejs
            - golang
          additional_repositories:
            - deb http://us.archive.ubuntu.com/ubuntu/ jammy universe
            - deb http://us.archive.ubuntu.com/ubuntu/ jammy-updates universe
            - deb http://security.ubuntu.com/ubuntu jammy-security universe
          zsh_aliases:
            - tf=terraform
            - tfa=terraform apply
            - tfp=terraform plan
            - tfw=terraform workspace
            - tfd=terraform destroy
            - k=kubectl
            - kgp=kubectl get pods
            - kgn=kubectl get namespaces
          zsh_plugins:
            - git
            - aws
            - docker
            - zsh-autosuggestions
            - zsh-syntax-highlighting
            - npm
            - golang
        razer-blade-stealth:
          ws_home_dir: "/home/username"
          ws_username: "username"
          ssh_configure: true
          os_type: "linux"
          architecture: "amd64"
          packages:
            - nodejs
            - golang
            - software-properties-gtk
            - openrazer-meta
            - polychromatic
          additional_repositories:
            - deb http://us.archive.ubuntu.com/ubuntu/ jammy universe
            - deb http://us.archive.ubuntu.com/ubuntu/ jammy-updates universe
            - deb http://security.ubuntu.com/ubuntu jammy-security universe
            - ppa:openrazer/stable
            - ppa:polychromatic/stable
          zsh_aliases:
            - tf=terraform
            - tfa=terraform apply
            - tfp=terraform plan
            - tfw=terraform workspace
            - tfd=terraform destroy
            - k=kubectl
            - kgp=kubectl get pods
            - kgn=kubectl get namespaces
          zsh_plugins:
            - git
            - aws
            - docker
            - zsh-autosuggestions
            - zsh-syntax-highlighting
            - npm
            - golang
